script: |
  docker stop frontend-app || true
  docker rm frontend-app || true

  rm -rf devops || true

  git clone https://github.com/Abineshwari-B/DevOps-Mini-Projects.git
  cd DevOps-Mini-Projects/CI-CD\ Pipeline\ for\ Dockerized\ App/Source\ Code

  docker build -t frontend-app .
  docker run -d -p 80:80 --name frontend-app frontend-app
